version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: hr_assistant
      POSTGRES_USER: hr_user
      POSTGRES_PASSWORD: hr_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hr_network

  # Redis for Celery
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - hr_network

  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://hr_user:hr_password@postgres:5432/hr_assistant
      - REDIS_URL=redis://redis:6379
      - DEBUG=True
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    networks:
      - hr_network

  # Celery Worker
  celery:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: celery -A app.services.scheduler worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://hr_user:hr_password@postgres:5432/hr_assistant
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app/app
    networks:
      - hr_network

  # Celery Beat (Scheduler)
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: celery -A app.services.scheduler beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://hr_user:hr_password@postgres:5432/hr_assistant
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app/app
    networks:
      - hr_network

  # Next.js Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    volumes:
      - ./app:/app/app
      - ./package.json:/app/package.json
      - ./next.config.js:/app/next.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
    networks:
      - hr_network

volumes:
  postgres_data:

networks:
  hr_network:
    driver: bridge